# DEMO: Tácticas de Binding para Modificabilidad
# TÁCTICA 1: Binding en tiempo de configuración

# Configuración de la API
api:
  service_name: "api-service"
  port: 8080

# TÁCTICA 1: Feature flags para modificar comportamiento sin recompilar
feature_flags:
  enable_notifications: true
  enable_reports: false
  maintenance_mode: true

# Configuración de logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR

# Configuración del entorno
environment:
  name: "development"  # development, staging, production
