version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - REGISTRY_URL=http://registry:8500

  registry:
    image: consul
    ports:
      - "8500:8500"
